laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'empresa', 'uses' => 'HomeController@empresa']);
Route::get('areas-de-atuacao', ['as' => 'atuacao', 'uses' => 'HomeController@atuacao']);
Route::get('cursos/{curso_slug?}', ['as' => 'cursos', 'uses' => 'HomeController@cursos']);
Route::get('pesquisa-e-desenvolvimento', ['as' => 'pesquisa', 'uses' => 'HomeController@pesquisa']);
Route::get('noticias/{noticia_slug?}', ['as' => 'noticias', 'uses' => 'HomeController@noticias']);
Route::get('contato', ['as' => 'contato', 'uses' => 'HomeController@contato']);
Route::post('contato', ['as' => 'contato.envio', 'uses' => 'HomeController@contatoEnvio']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);

    Route::resource('noticias', 'NoticiasController');
    Route::resource('noticias.arquivos', 'NoticiasArquivosController');
    Route::resource('cursos', 'CursosController');
    Route::resource('cursos.arquivos', 'CursosArquivosController');
    Route::resource('contatos-recebidos', 'ContatosRecebidosController');
    Route::resource('usuarios', 'UsuariosController');

    Route::post('ckeditor-upload', 'HomeController@imageUpload');

    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Models/Curso.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Illuminate\Database\Eloquent\Model;

class Curso extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $sluggable = [
        'build_from' => 'titulo',
        'save_to'    => 'slug',
        'on_update'  => true
    ];

    protected $table = 'cursos';

    protected $guarded = ['id'];

    public function scopeOrdenados($query)
    {
        return $query->orderBy('data', 'DESC')->orderBy('id', 'DESC');
    }

    public function scopeSlug($query, $slug)
    {
        return $query->whereSlug($slug);
    }

    public function arquivos()
    {
        return $this->hasMany('App\Models\CursoArquivo', 'curso_id')->orderBy('ordem', 'ASC')->orderBy('id', 'DESC');
    }

    public function setDataAttribute($date)
    {
        $this->attributes['data'] = Carbon::createFromFormat('d/m/Y', $date)->format('Y-m-d');
    }

    public function getDataAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d', $date)->format('d/m/Y');
    }
}

laravel/app/Http/Controllers/Painel/CursosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;
use App\Http\Requests\CursosRequest;

use App\Http\Controllers\Controller;

use App\Models\Curso;

class CursosController extends Controller
{
    public function index()
    {
        $cursos = Curso::ordenados()->get();

        return view('painel.cursos.index', compact('cursos'));
    }

    public function create()
    {
        return view('painel.cursos.create');
    }

    public function store(CursosRequest $request)
    {
        try {

            $input = $request->all();

            Curso::create($input);
            return redirect()->route('painel.cursos.index')->with('success', 'Curso adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar curso: '.$e->getMessage()]);

        }
    }

    public function edit(Curso $curso)
    {
        return view('painel.cursos.edit', compact('curso'));
    }

    public function update(CursosRequest $request, Curso $curso)
    {
        try {

            $input = $request->all();

            $curso->update($input);
            return redirect()->route('painel.cursos.index')->with('success', 'Curso alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar curso: '.$e->getMessage()]);

        }
    }

    public function destroy(Curso $curso)
    {
        try {

            $curso->delete();
            return redirect()->route('painel.cursos.index')->with('success', 'Curso excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir curso: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/cursos/arquivos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Cursos / {{ $curso->titulo }} /</small> Adicionar Arquivo</h2>
    </legend>

    {!! Form::open(['route' => ['painel.cursos.arquivos.store', $curso], 'files' => true]) !!}

        @include('painel.cursos.arquivos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/cursos/arquivos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Cursos / {{ $curso->titulo }} /</small> Editar Arquivo</h2>
    </legend>

    {!! Form::model($arquivo, [
        'route'  => ['painel.cursos.arquivos.update', $curso, $arquivo],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.cursos.arquivos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/cursos/arquivos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('arquivo', 'Arquivo') !!}
@if($submitText == 'Alterar' && $arquivo->arquivo)
    <a href="{{ url('assets/arquivos/'.$arquivo->arquivo) }}" target="_blank" style="display:block;margin:10px 0;">{{ $arquivo->arquivo }}</a>
@endif
    {!! Form::file('arquivo', ['class' => 'form-control']) !!}
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.cursos.arquivos.index', $curso) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/cursos/arquivos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <a href="{{ route('painel.cursos.index') }}" class="btn btn-sm btn-default">
        &larr; Voltar para Cursos
    </a>

    <legend>
        <h2>
            <small>Cursos / {{ $curso->titulo }} /</small> Arquivos
            <a href="{{ route('painel.cursos.arquivos.create', $curso) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Arquivo</a>
        </h2>
    </legend>

    @if(!count($arquivos))
    <div class="alert alert-warning" role="alert">Nenhum arquivo cadastrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-sortable" data-table="cursos_arquivos">
        <thead>
            <tr>
                <th>Ordem</th>
                <th>Arquivo</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($arquivos as $arquivo)
            <tr class="tr-row" id="{{ $arquivo->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td><a href="{{ url('assets/arquivos/'.$arquivo->arquivo) }}">{{ $arquivo->titulo }}</a></td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.cursos.arquivos.destroy', $curso, $arquivo],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.cursos.arquivos.edit', [$curso, $arquivo]) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection